How does convolution work? 

In [1]:
import numpy as np

In [4]:
patch = np.array([[1,1],
                [0,1]])
print(patch)

[[1 1]
 [0 1]]


In [5]:
kernel = np.array([[1,2],
                  [3,4]])
print(kernel)

[[1 2]
 [3 4]]


__This is not what we want...__

In [8]:
print('Matrix dot product: \n', np.dot(patch, kernel))

Matrix dot product: 
 [[4 6]
 [3 4]]


__This is what we want:__

In [11]:
print('Flattened patch: ', patch.flatten(), '\n', 'Flattened kernel: ', kernel.flatten())
print('Element-wise product: ', patch.flatten().dot(kernel.flatten()))

Flattened patch:  [1 1 0 1] 
 Flattened kernel:  [1 2 3 4]
Element-wise product:  7
